# -*- coding: utf-8 -*-
"""MLday_14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17U9xhpz8AUs29HC-JJYm7zA5kiXuW8VB
"""

import pandas as pd
import numpy as np

from google.colab import files
upload = files.upload()

dataset = pd.read_csv('data.csv')

print(dataset.shape)
print(dataset.head(5))

X = dataset.iloc[:, :-1].values
X

Y = dataset.iloc[:, -1]
Y

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

print(X_train.shape)
print(X_test.shape)

from sklearn.svm import SVR
model = SVR()
model.fit(X_train, Y_train)

ypred = model.predict(X_test)

from sklearn.metrics import r2_score, mean_squared_error
mse = mean_squared_error(Y_test, ypred)
rmse = np.square(mse)
print("mean squared error: ",rmse)
r_square = r2_score(Y_test, ypred)
print("r2 score: ",r_square*100)