# -*- coding: utf-8 -*-
"""ML_day_11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g82dJkdGPdYHKzInNJiJw7XETWklldO3
"""

import pandas as pd
import numpy as np

from google.colab import files
upload = files.upload()

dataset = pd.read_csv('dataset.csv')

print(dataset.shape)
print(dataset.head(5))

import matplotlib.pyplot as plt
plt.xlabel('Area')
plt.ylabel('Price')
plt.scatter(dataset.area,dataset.price,color='red',marker='*')

X = dataset.drop('price',axis='columns')
X

Y = dataset.price
Y



from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X, Y)

x = 40000
LandAreainSqFt=[[x]]
PredictedmodelResult = model.predict(LandAreainSqFt)
print(PredictedmodelResult)

m = model.coef_
print(m)

b = model.intercept_
print(b)



p = m*x + b
print(p)